
############################################################
# Script: 03_LimoRhyde_rhythmic_detection.R
# Project: Circadian gene expression analysis
#
# Description:
# Identification of rhythmic genes using LimoRhyde combined
# with limma linear modeling. Circadian oscillations are modeled
# using sine and cosine terms with a 24-hour period.
#
# The analysis is performed independently in seeds and leaves
# to identify organ-specific circadian-regulated genes.
#
# Input:
# - Normalized expression matrix generated by DESeq2 VST
# - Sample metadata file
#
# Output:
# - LimoRhyde rhythmicity results for seeds
# - LimoRhyde rhythmicity results for leaves
# - Number of significant rhythmic genes
#
# Author: Fatoumata KAMISSOKO
############################################################



## Load libraries -------------------------------------------------------------

library(data.table)
library(limma)
library(limorhyde)



## Define paths ---------------------------------------------------------------

expression_file <- "outputs/data/Expressed.vst.txt"
metadata_file <- "data/raw/Metadata.txt"

output_dir <- "outputs/data"



## Load expression data and metadata -------------------------------------------

expression <- read.table(
  expression_file,
  header = TRUE,
  sep = "\t"
)


metadata <- read.table(
  metadata_file,
  header = TRUE,
  sep = "\t"
)



## Prepare metadata -----------------------------------------------------------

row.names(metadata) <- metadata$SampleName


# Convert Zeitgeber time (ZT) into numeric values

metadata$ZTnum <- as.numeric(
  sub("ZT", "", metadata$Time)
)



# Generate circadian variables using LimoRhyde

time_terms <- limorhyde(
  metadata$ZTnum,
  period = 24
)


metadata <- cbind(
  metadata,
  time_terms
)


colnames(metadata)[
  (ncol(metadata)-1):ncol(metadata)
] <- c(
  "time_cos",
  "time_sin"
)



## Prepare expression matrix --------------------------------------------------

expr <- expression

rownames(expr) <- expr$ID

expr$ID <- NULL

expr <- as.matrix(expr)



############################################################
# 1. Rhythmic genes in seeds
############################################################


organ <- "S"


metadata_seed <- metadata[
  metadata$Organ == organ,
]


seed_samples <- metadata_seed$SampleName



# Select seed expression data

expression_seed <- expr[
  ,
  colnames(expr) %in% seed_samples
]


# Reorder metadata according to expression matrix

metadata_seed <- metadata_seed[
  match(
    colnames(expression_seed),
    metadata_seed$SampleName
  ),
]



## Circadian design matrix

design_seed <- model.matrix(
  ~ time_cos + time_sin,
  data = metadata_seed
)



## Limma model

fit_seed <- lmFit(
  expression_seed,
  design_seed
)


fit_seed <- eBayes(
  fit_seed,
  trend = TRUE
)



## Extract rhythmic genes

rhy_seed <- data.table(
  topTable(
    fit_seed,
    coef = 2:3,
    number = Inf
  ),
  keep.rownames = TRUE
)


setnames(
  rhy_seed,
  "rn",
  "gene_id"
)



# Adjust p-values

rhy_seed[, adj.P.Val :=
           p.adjust(
             P.Value,
             method = "BH"
           )
]


# Define rhythmic genes

rhy_seed[, Rhythmic :=
           adj.P.Val < 0.05
]


nb_rhythmic_seed <- sum(
  rhy_seed$Rhythmic
)



############################################################
# 2. Rhythmic genes in leaves
############################################################


organ <- "L"


metadata_leaf <- metadata[
  metadata$Organ == organ,
]


leaf_samples <- metadata_leaf$SampleName



# Select leaf expression data

expression_leaf <- expr[
  ,
  colnames(expr) %in% leaf_samples
]



# Reorder metadata

metadata_leaf <- metadata_leaf[
  match(
    colnames(expression_leaf),
    metadata_leaf$SampleName
  ),
]



## Circadian design matrix

design_leaf <- model.matrix(
  ~ time_cos + time_sin,
  data = metadata_leaf
)



## Limma model

fit_leaf <- lmFit(
  expression_leaf,
  design_leaf
)


fit_leaf <- eBayes(
  fit_leaf,
  trend = TRUE
)



## Extract rhythmic genes

rhy_leaf <- data.table(
  topTable(
    fit_leaf,
    coef = 2:3,
    number = Inf
  ),
  keep.rownames = TRUE
)


setnames(
  rhy_leaf,
  "rn",
  "gene_id"
)



# Adjust p-values

rhy_leaf[, adj.P.Val :=
           p.adjust(
             P.Value,
             method = "BH"
           )
]


# Define rhythmic genes

rhy_leaf[, Rhythmic :=
           adj.P.Val < 0.05
]


nb_rhythmic_leaf <- sum(
  rhy_leaf$Rhythmic
)



############################################################
# Export results
############################################################


write.table(
  rhy_seed,
  file.path(
    output_dir,
    "LimoRhyde_rhythmic_genes_seeds.txt"
  ),
  sep = "\t",
  quote = FALSE,
  row.names = FALSE
)



write.table(
  rhy_leaf,
  file.path(
    output_dir,
    "LimoRhyde_rhythmic_genes_leaves.txt"
  ),
  sep = "\t",
  quote = FALSE,
  row.names = FALSE
)



write.table(
  nb_rhythmic_seed,
  file.path(
    output_dir,
    "number_rhythmic_genes_seeds.txt"
  ),
  sep = "\t",
  quote = FALSE,
  row.names = FALSE
)



write.table(
  nb_rhythmic_leaf,
  file.path(
    output_dir,
    "number_rhythmic_genes_leaves.txt"
  ),
  sep = "\t",
  quote = FALSE,
  row.names = FALSE
)



## Summary --------------------------------------------------------------------

cat(
  "Number of rhythmic genes in seeds:",
  nb_rhythmic_seed,
  "\n"
)


cat(
  "Number of rhythmic genes in leaves:",
  nb_rhythmic_leaf,
  "\n"
)