############################################################
# Script: 05_Differentially_rhythmic_analysis.R
# Project: Circadian transcriptomic gene expression analysis 
#
# Description:
# Identification of differentially rhythmic genes between leaves
# and seeds using a limma-based circadian interaction model.
#
# The model tests whether circadian expression patterns differ
# between organs by evaluating the interaction between organ
# identity and rhythmic components (cosine and sine terms).
#
# Input:
# - Normalized expression matrix generated by DESeq2 VST
# - Sample metadata
# - Lists of rhythmic genes identified by MetaCycle/LimoRhyde
#
# Output:
# - Differential rhythmicity statistics
# - Significant differentially rhythmic genes
# - Non-significant rhythmic genes
#
# Author: Fatim1401
############################################################



## Load libraries -------------------------------------------------------------

library(data.table)
library(limma)
library(limorhyde)



## Define paths ---------------------------------------------------------------

expression_file <- "outputs/data/Expressed.vst.txt"
metadata_file <- "data/raw/Metadata.txt"

common_seed_file <- "outputs/data/common_rhythmic_genes_seeds.txt"
common_leaf_file <- "outputs/data/common_rhythmic_genes_leaves.txt"

output_dir <- "outputs/data"



## Load data ------------------------------------------------------------------

expression <- read.table(
  expression_file,
  header = TRUE,
  sep = "\t"
)


metadata <- read.table(
  metadata_file,
  header = TRUE,
  sep = "\t"
)



## Prepare metadata -----------------------------------------------------------

row.names(metadata) <- metadata$SampleName


metadata$Organ <- factor(
  metadata$Organ
)


# Convert ZT time into numeric

metadata$ZTnum <- as.numeric(
  sub(
    "ZT",
    "",
    metadata$Time
  )
)



# Generate circadian variables

time_terms <- limorhyde(
  metadata$ZTnum,
  period = 24
)


metadata <- cbind(
  metadata,
  time_terms
)



colnames(metadata)[
  (ncol(metadata)-1):ncol(metadata)
] <- c(
  "time_cos",
  "time_sin"
)



## Prepare expression matrix --------------------------------------------------

expr <- expression

rownames(expr) <- expr$ID

expr$ID <- NULL

expr <- as.matrix(expr)



############################################################
# Select genes rhythmic in both organs
############################################################


rhythmic_seed <- read.table(
  common_seed_file,
  header = FALSE,
  stringsAsFactors = FALSE
)


rhythmic_leaf <- read.table(
  common_leaf_file,
  header = FALSE,
  stringsAsFactors = FALSE
)


genes_rhythmic <- intersect(
  rhythmic_seed$V1,
  rhythmic_leaf$V1
)



cat(
  "Number of genes analysed for differential rhythmicity:",
  length(genes_rhythmic),
  "\n"
)



# Keep only rhythmic genes

expr_dr <- expr[
  rownames(expr) %in% genes_rhythmic,
]



############################################################
# Prepare expression and metadata
############################################################


sample_ids <- metadata$SampleName


expr_dr <- expr_dr[
  ,
  colnames(expr_dr) %in% sample_ids
]


# Reorder metadata

metadata <- metadata[
  match(
    colnames(expr_dr),
    metadata$SampleName
  ),
]



############################################################
# Differential rhythmicity model
############################################################


# Interaction model:
# Organ x circadian rhythm

design <- model.matrix(
  ~ Organ * (time_cos + time_sin),
  data = metadata
)



colnames(design)



## Fit limma model

fit <- lmFit(
  expr_dr,
  design
)


fit <- eBayes(
  fit,
  trend = TRUE
)



############################################################
# Extract differential rhythmicity results
############################################################


# Interaction coefficients correspond to:
# difference in cosine and sine rhythmic patterns
# between organs


dr_results <- data.table(
  topTable(
    fit,
    coef = grep(
      "Organ.*time",
      colnames(design)
    ),
    number = Inf
  ),
  keep.rownames = TRUE
)



setnames(
  dr_results,
  "rn",
  "gene_id"
)



# Adjust p-values

dr_results[
  ,
  adj.P.Val :=
    p.adjust(
      P.Value,
      method = "BH"
    )
]



# Define differential rhythmic genes

dr_results[
  ,
  DiffRhythmic :=
    adj.P.Val < 0.05
]



############################################################
# Separate significant and non-significant genes
############################################################


dr_rhythmic <- dr_results[
  DiffRhythmic == TRUE,
]


ndr_rhythmic <- dr_results[
  DiffRhythmic == FALSE,
]



cat(
  "Differentially rhythmic genes:",
  nrow(dr_rhythmic),
  "\n"
)



############################################################
# Export results
############################################################


write.table(
  dr_results,
  file.path(
    output_dir,
    "differential_rhythmicity_results.txt"
  ),
  sep = "\t",
  quote = FALSE,
  row.names = FALSE
)



write.table(
  dr_rhythmic,
  file.path(
    output_dir,
    "differentially_rhythmic_genes.txt"
  ),
  sep = "\t",
  quote = FALSE,
  row.names = FALSE
)



write.table(
  ndr_rhythmic,
  file.path(
    output_dir,
    "non_differentially_rhythmic_genes.txt"
  ),
  sep = "\t",
  quote = FALSE,
  row.names = FALSE
)



############################################################
# Summary
############################################################


cat("---------------------------------\n")

cat(
  "Total tested rhythmic genes:",
  nrow(dr_results),
  "\n"
)

cat(
  "Differentially rhythmic genes:",
  nrow(dr_rhythmic),
  "\n"
)

cat(
  "Non-differentially rhythmic genes:",
  nrow(ndr_rhythmic),
  "\n"
)